server:
  port: 8080
    
spring:
  application:
    name: snackshare

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/snackshare}
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

logging:
  level:
    root: INFO
    
redis:
  host: ${REDIS_HOST:127.0.0.1}
  port: 6379
  
snackshare:
  backend:
    url: http://localhost:8080/snackShare/order
  payments:
    url:
      picpay : http://www.picpay.com.br/ 
      
      
      
      