server:
  port: 8080

spring:
  application:
    name: snackshare

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    root: INFO

snackshare:
  backend: 
    url: http://localhost:7001/snackShare/