server:
  port: 7001
    
spring:
  application:
    name: snackshare

logging:
  level:
    root: DEBUG

snackshare:
  payments:

    pix:
      receiver:
       name: Mário Romeu da Silva Junior
       city: Salvador
       pix-key: 02525440560

    security:
      ssl-certificate-full-path-and-name: trust.jks

    picpay:
      url: https://appws.picpay.com/ecommerce/public/
      x-picpay-token: 0
      x-seller-token: 0

    brcode:
      url: https://gerarqrcodepix.com.br/api/v1/

    braspag:
      url:
        service: https://apisandbox.braspag.com.br/v2/sales/
        search: https://apiquerysandbox.braspag.com.br/v2/sales/
      merchantId: 0f8557f2-6a0f-4a70-a25b-5aabcbae845a
      merchantKey: UAVYJXUURHGSYPSHTNJBXTPSEOGUGJQZPBOJRPCN
