server:
  port: 7001
    
spring:
  application:
    name: snackshare

logging:
  level:
    root: DEBUG

snackshare:
  payments:
    pix:
      receiver:
       name: Mario Romeu da Silva Junior
       city: Salvador
       pix: mario.romeu@gmail.com
    picpay:
      security:
        ssl-certificate-full-path-and-name: trust.jks
      url: https://appws.picpay.com/ecommerce/public/      
      x-picpay-token: 0
      x-seller-token: 0
    brcode:
      security:
        ssl-certificate-full-path-and-name: src/main/resources/gerarqrcodepix.cert
      url: 
        service: https://gerarqrcodepix.com.br/api/v1/
    braspag:
      security:
        ssl-certificate-full-path-and-name: trust.jks
      url:
        service: https://apisandbox.braspag.com.br/v2/sales/
        search: https://apiquerysandbox.braspag.com.br/v2/sales/
      merchantId: 0f8557f2-6a0f-4a70-a25b-5aabcbae845a
      merchantKey: UAVYJXUURHGSYPSHTNJBXTPSEOGUGJQZPBOJRPCN